<?php

namespace Boostit\WebBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductLoggerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductLoggerRepository extends EntityRepository
{
}
